apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  containers:
  - name: debug
    image: alpine:latest
    command:
      - "sleep"
      - "10000"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
